Basic RT components and utilities: python.hrpsys_config.HrpsysConfigurator Class Reference
python.hrpsys_config.HrpsysConfigurator Class Reference
Public Member Functions
def connectComps
Connect components(plugins)
def activateComps
Activate components(plugins)
def createComp
Create RTC component (plugins)
def createComps
Create components(plugins) in getRTCList()
def findComp
Find component(plugin)
def findComps
Check if all components in getRTCList() are created.
def getRTCList
Get list of available STABLE components.
def getRTCListUnstable
Get list of available components including stable and unstable.
def getJointAngleControllerList
Get list of controller list that need to control joint angles.
def getRTCInstanceList
Get list of RTC Instance.
def getBodyInfo
Get bodyInfo.
def getSensors
Get list of sensors.
def connectLoggerPort
Connect port to logger.
def setupLogger
Setup logging function.
def waitForRTCManager
Wait for RTC manager.
def waitForRobotHardware
Wait for RobotHardware is exists and activated.
def checkSimulationMode
Check if this is running as simulation.
def waitForRTCManagerAndRoboHardware
Wait for both RTC Manager (waitForRTCManager()) and RobotHardware (waitForRobotHardware())
def findModelLoader
Try to find ModelLoader.
def waitForModelLoader
Wait for ModelLoader.
def setSelfGroups
Set to the hrpsys.SequencePlayer the groups of links and joints that are statically defined as member variables (Groups) within this class.
def goActual
Adjust commanded values to the angles in the physical state by calling StateHolder::goActual.
def setJointAngle
Set angle to the given joint.
def setJointAngles
Set all joint angles.
def setJointAnglesOfGroup
Set the joint angles to aim.
def loadPattern
Load a pattern file that is created offline.
def waitInterpolation
Lets SequencePlayer wait until the movement currently happening to finish.
def waitInterpolationOfGroup
Lets SequencePlayer wait until the movement currently happening to finish.
def getJointAngles
Returns the commanded joint angle values.
def getCurrentPose
Returns the current physical pose of the specified joint.
def getCurrentPosition
Returns the current physical position of the specified joint.
def getCurrentRotation
Returns the current physical rotation of the specified joint.
def getCurrentRPY
Returns the current physical rotation in RPY of the specified joint.
def getReferencePose
Returns the current commanded pose of the specified joint.
def getReferencePosition
Returns the current commanded position of the specified joint.
def getReferenceRotation
Returns the current commanded rotation of the specified joint.
def getReferenceRPY
Returns the current commanded rotation in RPY of the specified joint.
def setTargetPose
Set absolute pose to a joint.
def setTargetPoseRelative
Set angles to a joint group relative to its current pose.
def clear
Clears the Sequencer's current operation.
def clearOfGroup
Clears the Sequencer's current operation for joint groups.
def saveLog
Save log to the given file name.
def clearLog
Clear logger's buffer.
def lengthDigitalInput
Returns the length of digital input port.
def lengthDigitalOutput
Returns the length of digital output port.
def writeDigitalOutput
Using writeDigitalOutputWithMask is recommended for the less data transport.
def writeDigitalOutputWithMask
Both dout and mask are lists with length of 32.
def readDigitalInput
Read data from Digital Input.
def readDigitalOutput
Read data from Digital Output.
def getActualState
Get actual states of the robot that includes current reference joint angles and joint torques.
def isCalibDone
Check whether joints have been calibrated.
def isServoOn
Check whether servo control has been turned on.
def flat2Groups
Convert list of angles into list of joint list for each groups.
def servoOn
Turn on servos.
def servoOff
Turn off servos.
def checkEncoders
Run the encoder checking sequence for specified joints, run goActual and turn on servos.
def removeForceSensorOffset
remove force sensor offset
def playPattern
Play motion pattern using a given trajectory that is represented by a list of joint angles, rpy, zmp and time.
def playPatternOfGroup
Play motion pattern using a given trajectory that is represented by a list of joint angles.
def init
Calls init from its superclass, which tries to connect RTCManager, looks for ModelLoader, and starts necessary RTC components.
def __init__
Public Attributes
configurator_name
Static Public Attributes
rh = None
rh_svc = None
ep_svc = None
rh_version = None
seq = None
seq_svc = None
seq_version = None
sh = None
sh_svc = None
sh_version = None
fk = None
fk_svc = None
fk_version = None
tf = None
kf = None
vs = None
rmfo = None
ic = None
abc = None
st = None
tf_version = None
kf_version = None
vs_version = None
rmfo_version = None
ic_version = None
abc_version = None
st_version = None
co = None
co_svc = None
co_version = None
gc = None
gc_svc = None
gc_version = None
el = None
el_svc = None
el_version = None
te = None
te_svc = None
te_version = None
tl = None
tl_svc = None
tl_version = None
tc = None
tc_svc = None
tc_version = None
log = None
log_svc = None
log_version = None
ms = None
hgc = None
pdc = None
simulation_mode = None
sensors = None
list Groups = []
Constructor & Destructor Documentation
def python.hrpsys_config.HrpsysConfigurator.__init__ (self, cname = "[hrpsys.py] ")
Member Function Documentation
def python.hrpsys_config.HrpsysConfigurator.activateComps (self)
Activate components(plugins)
References python.hrpsys_config.HrpsysConfigurator.getRTCInstanceList().
Referenced by python.hrpsys_config.HrpsysConfigurator.init().
def python.hrpsys_config.HrpsysConfigurator.checkEncoders (self, jname = 'all', option = '')
Run the encoder checking sequence for specified joints, run goActual and turn on servos.
Parameters:
jname str: The value 'all' works iteratively for all servos.
option str: Possible values are follows (w/o double quote):\ "-overwrite": Overwrite calibration value.
References python.hrpsys_config.HrpsysConfigurator.configurator_name, python.hrpsys_config.HrpsysConfigurator.goActual(), python.hrpsys_config.HrpsysConfigurator.isCalibDone(), and python.hrpsys_config.HrpsysConfigurator.isServoOn().
def python.hrpsys_config.HrpsysConfigurator.checkSimulationMode (self)
Check if this is running as simulation.
References python.hrpsys_config.HrpsysConfigurator.configurator_name, python.hrpsys_config.HrpsysConfigurator.ep_svc, python::rtm.findRTC(), python.hrpsys_config.HrpsysConfigurator.hgc, python::rtm.narrow(), python.hrpsys_config.HrpsysConfigurator.pdc, python.hrpsys_config.HrpsysConfigurator.rh, python.hrpsys_config.HrpsysConfigurator.rh_svc, and python.hrpsys_config.HrpsysConfigurator.simulation_mode.
Referenced by python.hrpsys_config.HrpsysConfigurator.waitForRTCManagerAndRoboHardware().
def python.hrpsys_config.HrpsysConfigurator.clear (self)
Clears the Sequencer's current operation.
Works for joint groups too.
See also:
HrpsysConfigurator.clear
Discussed in https://github.com/fkanehiro/hrpsys-base/issues/158 Examples is found in a unit test: https://github.com/start-jsk/rtmros_hironx/blob/bb0672be3e03e5366e03fe50520e215302b8419f/hironx_ros_bridge/test/test_hironx.py#L293
def python.hrpsys_config.HrpsysConfigurator.clearLog (self)
Clear logger's buffer.
def python.hrpsys_config.HrpsysConfigurator.clearOfGroup (self, gname, tm = 0.0)
Clears the Sequencer's current operation for joint groups.
def python.hrpsys_config.HrpsysConfigurator.connectComps (self)
Connect components(plugins)
References python.hrpsys_config.HrpsysConfigurator.abc, python.hrpsys_config.HrpsysConfigurator.co, python.hrpsys_config.HrpsysConfigurator.configurator_name, python::rtm.connectPorts(), python.hrpsys_config.HrpsysConfigurator.el, python.hrpsys_config.HrpsysConfigurator.fk, python.hrpsys_config.HrpsysConfigurator.gc, python.hrpsys_config.HrpsysConfigurator.getJointAngleControllerList(), python.hrpsys_config.HrpsysConfigurator.ic, python.hrpsys_config.HrpsysConfigurator.kf, python.hrpsys_config.HrpsysConfigurator.pdc, python.hrpsys_config.HrpsysConfigurator.rh, python.hrpsys_config.HrpsysConfigurator.rmfo, python.hrpsys_config.HrpsysConfigurator.sensors, python.hrpsys_config.HrpsysConfigurator.seq, python.hrpsys_config.HrpsysConfigurator.sh, python.hrpsys_config.HrpsysConfigurator.simulation_mode, python.hrpsys_config.HrpsysConfigurator.st, python.hrpsys_config.HrpsysConfigurator.tc, python.hrpsys_config.HrpsysConfigurator.te, python.hrpsys_config.HrpsysConfigurator.tf, python.hrpsys_config.HrpsysConfigurator.tl, and python.hrpsys_config.HrpsysConfigurator.vs.
Referenced by python.hrpsys_config.HrpsysConfigurator.init().
def python.hrpsys_config.HrpsysConfigurator.connectLoggerPort (self, artc, sen_name, log_name = None)
Connect port to logger.
Parameters:
artc object: object of component that contains sen_name port
sen_name str: name of port for logging
log_name str: name of port in logger
References python.hrpsys_config.HrpsysConfigurator.configurator_name, python::rtm.connectPorts(), and python.hrpsys_config.HrpsysConfigurator.log.
Referenced by python.hrpsys_config.HrpsysConfigurator.setupLogger().
def python.hrpsys_config.HrpsysConfigurator.createComp (self, compName, instanceName)
Create RTC component (plugins)
Parameters:
instanceName str: name of instance, choose one of https://github.com/fkanehiro/hrpsys-base/tree/master/rtc
comName str: name of component that to be created.
References python.hrpsys_config.HrpsysConfigurator.configurator_name, and python::rtm.narrow().
def python.hrpsys_config.HrpsysConfigurator.createComps (self)
Create components(plugins) in getRTCList()
References python.hrpsys_config.HrpsysConfigurator.configurator_name, and python.hrpsys_config.HrpsysConfigurator.getRTCList().
Referenced by python.hrpsys_config.HrpsysConfigurator.init().
def python.hrpsys_config.HrpsysConfigurator.findComp (self, compName, instanceName, max_timeout_count = 10)
Find component(plugin)
Parameters:
compName str: component name
instanceName str: instance name int: max timeout in seconds
References python.hrpsys_config.HrpsysConfigurator.configurator_name, and python::rtm.narrow().
def python.hrpsys_config.HrpsysConfigurator.findComps (self)
Check if all components in getRTCList() are created.
References python.hrpsys_config.HrpsysConfigurator.configurator_name, and python.hrpsys_config.HrpsysConfigurator.getRTCList().
def python.hrpsys_config.HrpsysConfigurator.findModelLoader (self)
Try to find ModelLoader.
Referenced by python.hrpsys_config.HrpsysConfigurator.waitForModelLoader().
def python.hrpsys_config.HrpsysConfigurator.flat2Groups (self, flatList)
Convert list of angles into list of joint list for each groups.
Parameters:
flatList list: single dimension list with its length of 15
Returns:
list of list: 2-dimensional list of Groups.
References python.hrpsys_config.HrpsysConfigurator.Groups.
def python.hrpsys_config.HrpsysConfigurator.getActualState (self)
Get actual states of the robot that includes current reference joint angles and joint torques.
Returns:
: This returns actual states of the robot, which is defined in RobotHardware.idl (https://github.com/fkanehiro/hrpsys-base/blob/master/idl/RobotHardwareService.idl#L33)
    /**
     * @brief status of the robot
     */
    struct RobotState
    {
      DblSequence               angle;  ///< current joint angles[rad]
      DblSequence               command;///< reference joint angles[rad]
      DblSequence               torque; ///< joint torques[Nm]
      /**
       * @brief servo statuses(32bit+extra states)
       *
       * 0: calib status ( 1 => done )\n
       * 1: servo status ( 1 => on )\n
       * 2: power status ( 1 => supplied )\n
       * 3-18: servo alarms (see @ref iob.h)\n
       * 19-23: unused
       * 24-31: driver temperature (deg)
       */
      LongSequenceSequence              servoState;
      sequence<DblSequence6>    force;    ///< forces[N] and torques[Nm]
      sequence<DblSequence3>    rateGyro; ///< angular velocities[rad/s]
      sequence<DblSequence3>    accel;    ///< accelerations[m/(s^2)]
      double                    voltage;  ///< voltage of power supply[V]
      double                    current;  ///< current[A]
    };
Referenced by python.hrpsys_config.HrpsysConfigurator.isServoOn().
def python.hrpsys_config.HrpsysConfigurator.getBodyInfo (self, url)
Get bodyInfo.
References python.hrpsys_config.HrpsysConfigurator.configurator_name.
Referenced by python.hrpsys_config.HrpsysConfigurator.getSensors().
def python.hrpsys_config.HrpsysConfigurator.getCurrentPose (self, lname = None, frame_name = None)
Returns the current physical pose of the specified joint.
cf. getReferencePose that returns commanded value.
eg.
     IN: robot.getCurrentPose('LARM_JOINT5')
     OUT: [-0.0017702356144599085,
      0.00019034630541264752,
      -0.9999984150158207,
      0.32556275164378523,
      0.00012155879975329215,
      0.9999999745367515,
       0.0001901314142046251,
       0.18236394191140365,
       0.9999984257434246,
       -0.00012122202968358842,
       -0.001770258707652326,
       0.07462472659364472,
       0.0,
       0.0,
       0.0,
       1.0]
lname: str
Parameters:
lname,: Name of the link.
frame_name str: set reference frame name (from 315.2.5) : list of float
Returns:
: Rotational matrix and the position of the given joint in 1-dimensional list, that is:
 [a11, a12, a13, x,
  a21, a22, a23, y,
  a31, a32, a33, z,
   0,   0,   0,  1]
References python.hrpsys_config.HrpsysConfigurator.fk_version, python.hrpsys_config.HrpsysConfigurator.getCurrentPose(), and python.hrpsys_config.HrpsysConfigurator.Groups.
Referenced by python.hrpsys_config.HrpsysConfigurator.getCurrentPose(), python.hrpsys_config.HrpsysConfigurator.getCurrentPosition(), and python.hrpsys_config.HrpsysConfigurator.getCurrentRotation().
def python.hrpsys_config.HrpsysConfigurator.getCurrentPosition (self, lname = None, frame_name = None)
Returns the current physical position of the specified joint.
cf. getReferencePosition that returns commanded value.
eg.
    robot.getCurrentPosition('LARM_JOINT5')
    [0.325, 0.182, 0.074]
lname: str
Parameters:
lname,: Name of the link.
frame_name str: set reference frame name (from 315.2.5) : list of float
Returns:
: List of x, y, z positions about the specified joint.
References python.hrpsys_config.HrpsysConfigurator.getCurrentPose(), python.hrpsys_config.HrpsysConfigurator.getCurrentPosition(), and python.hrpsys_config.HrpsysConfigurator.Groups.
Referenced by python.hrpsys_config.HrpsysConfigurator.getCurrentPosition().
def python.hrpsys_config.HrpsysConfigurator.getCurrentRotation (self, lname, frame_name = None)
Returns the current physical rotation of the specified joint.
cf. getReferenceRotation that returns commanded value.
lname: str
Parameters:
lname,: Name of the link.
frame_name str: set reference frame name (from 315.2.5) : list of float
Returns:
: Rotational matrix of the given joint in 2-dimensional list, that is:
 [[a11, a12, a13],
  [a21, a22, a23],
  [a31, a32, a33]]
References python.hrpsys_config.HrpsysConfigurator.getCurrentPose(), python.hrpsys_config.HrpsysConfigurator.getCurrentRotation(), and python.hrpsys_config.HrpsysConfigurator.Groups.
Referenced by python.hrpsys_config.HrpsysConfigurator.getCurrentRotation(), and python.hrpsys_config.HrpsysConfigurator.getCurrentRPY().
def python.hrpsys_config.HrpsysConfigurator.getCurrentRPY (self, lname, frame_name = None)
Returns the current physical rotation in RPY of the specified joint.
cf. getReferenceRPY that returns commanded value.
lname: str
Parameters:
lname,: Name of the link.
frame_name str: set reference frame name (from 315.2.5) : list of float
Returns:
: List of orientation in rpy form about the specified joint.
References python::hrpsys_config.euler_from_matrix(), python.hrpsys_config.HrpsysConfigurator.getCurrentRotation(), python.hrpsys_config.HrpsysConfigurator.getCurrentRPY(), and python.hrpsys_config.HrpsysConfigurator.Groups.
Referenced by python.hrpsys_config.HrpsysConfigurator.getCurrentRPY().
def python.hrpsys_config.HrpsysConfigurator.getJointAngleControllerList (self)
Get list of controller list that need to control joint angles.
References python.hrpsys_config.HrpsysConfigurator.abc, python.hrpsys_config.HrpsysConfigurator.co, python.hrpsys_config.HrpsysConfigurator.el, python.hrpsys_config.HrpsysConfigurator.gc, python.hrpsys_config.HrpsysConfigurator.ic, python.hrpsys_config.HrpsysConfigurator.st, and python.hrpsys_config.HrpsysConfigurator.tc.
Referenced by python.hrpsys_config.HrpsysConfigurator.connectComps().
def python.hrpsys_config.HrpsysConfigurator.getJointAngles (self)
Returns the commanded joint angle values.
See also:
: HrpsysConfigurator.getJointAngles
Note that it's not the physical state of the robot's joints, which can be obtained by getActualState().angle.
Returns:
List of float: List of angles (degree) of all joints, in the order defined in the member variable 'Groups' (eg. chest, head1, head2, ..).
def python.hrpsys_config.HrpsysConfigurator.getReferencePose (self, lname, frame_name = None)
Returns the current commanded pose of the specified joint.
cf. getCurrentPose that returns physical pose.
lname: str
Parameters:
lname,: Name of the link.
frame_name str: set reference frame name (from 315.2.5) : list of float
Returns:
: Rotational matrix and the position of the given joint in 1-dimensional list, that is:
 [a11, a12, a13, x,
  a21, a22, a23, y,
  a31, a32, a33, z,
   0,   0,   0,  1]
References python.hrpsys_config.HrpsysConfigurator.fk_version, python.hrpsys_config.HrpsysConfigurator.getReferencePose(), and python.hrpsys_config.HrpsysConfigurator.Groups.
Referenced by python.hrpsys_config.HrpsysConfigurator.getReferencePose(), python.hrpsys_config.HrpsysConfigurator.getReferencePosition(), and python.hrpsys_config.HrpsysConfigurator.getReferenceRotation().
def python.hrpsys_config.HrpsysConfigurator.getReferencePosition (self, lname, frame_name = None)
Returns the current commanded position of the specified joint.
cf. getCurrentPosition that returns physical value.
lname: str
Parameters:
lname,: Name of the link.
frame_name str: set reference frame name (from 315.2.5) : list of float
Returns:
: List of angles (degree) of all joints, in the order defined in the member variable 'Groups' (eg. chest, head1, head2, ..).
References python.hrpsys_config.HrpsysConfigurator.getReferencePose(), python.hrpsys_config.HrpsysConfigurator.getReferencePosition(), and python.hrpsys_config.HrpsysConfigurator.Groups.
Referenced by python.hrpsys_config.HrpsysConfigurator.getReferencePosition().
def python.hrpsys_config.HrpsysConfigurator.getReferenceRotation (self, lname, frame_name = None)
Returns the current commanded rotation of the specified joint.
cf. getCurrentRotation that returns physical value.
lname: str
Parameters:
lname,: Name of the link.
frame_name str: set reference frame name (from 315.2.5) : list of float
Returns:
: Rotational matrix of the given joint in 2-dimensional list, that is:
 [[a11, a12, a13],
  [a21, a22, a23],
  [a31, a32, a33]]
References python.hrpsys_config.HrpsysConfigurator.getReferencePose(), and python.hrpsys_config.HrpsysConfigurator.Groups.
Referenced by python.hrpsys_config.HrpsysConfigurator.getReferenceRPY().
def python.hrpsys_config.HrpsysConfigurator.getReferenceRPY (self, lname, frame_name = None)
Returns the current commanded rotation in RPY of the specified joint.
cf. getCurrentRPY that returns physical value.
lname: str
Parameters:
lname,: Name of the link.
frame_name str: set reference frame name (from 315.2.5) : list of float
Returns:
: List of orientation in rpy form about the specified joint.
References python::hrpsys_config.euler_from_matrix(), python.hrpsys_config.HrpsysConfigurator.getReferenceRotation(), python.hrpsys_config.HrpsysConfigurator.getReferenceRPY(), and python.hrpsys_config.HrpsysConfigurator.Groups.
Referenced by python.hrpsys_config.HrpsysConfigurator.getReferenceRPY().
def python.hrpsys_config.HrpsysConfigurator.getRTCInstanceList (self)
Get list of RTC Instance.
References python.hrpsys_config.HrpsysConfigurator.getRTCList(), and python.hrpsys_config.HrpsysConfigurator.rh.
Referenced by python.hrpsys_config.HrpsysConfigurator.activateComps().
def python.hrpsys_config.HrpsysConfigurator.getRTCList (self)
Get list of available STABLE components.
Returns:
list of list: List of available components. Each element consists of a list of abbreviated and full names of the component.
Referenced by python.hrpsys_config.HrpsysConfigurator.createComps(), python.hrpsys_config.HrpsysConfigurator.findComps(), and python.hrpsys_config.HrpsysConfigurator.getRTCInstanceList().
def python.hrpsys_config.HrpsysConfigurator.getRTCListUnstable (self)
Get list of available components including stable and unstable.
Returns:
list of list: List of available unstable components. Each element consists of a list of abbreviated and full names of the component.
def python.hrpsys_config.HrpsysConfigurator.getSensors (self, url)
Get list of sensors.
Parameters:
url str: model file url
References python.hrpsys_config.HrpsysConfigurator.getBodyInfo().
Referenced by python.hrpsys_config.HrpsysConfigurator.init().
def python.hrpsys_config.HrpsysConfigurator.goActual (self)
Adjust commanded values to the angles in the physical state by calling StateHolder::goActual.
This needs to be run BEFORE servos are turned on.
Referenced by python.hrpsys_config.HrpsysConfigurator.checkEncoders(), and python.hrpsys_config.HrpsysConfigurator.servoOn().
def python.hrpsys_config.HrpsysConfigurator.init (self, robotname = "Robot", url = "")
Calls init from its superclass, which tries to connect RTCManager, looks for ModelLoader, and starts necessary RTC components.
Also runs config, logger. Also internally calls setSelfGroups().
robotname: str url: str
References python.hrpsys_config.HrpsysConfigurator.activateComps(), python.hrpsys_config.HrpsysConfigurator.configurator_name, python.hrpsys_config.HrpsysConfigurator.connectComps(), python.hrpsys_config.HrpsysConfigurator.createComps(), python.hrpsys_config.HrpsysConfigurator.getSensors(), python.hrpsys_config.HrpsysConfigurator.sensors, python.hrpsys_config.HrpsysConfigurator.setSelfGroups(), python.hrpsys_config.HrpsysConfigurator.setupLogger(), python.hrpsys_config.HrpsysConfigurator.waitForModelLoader(), and python.hrpsys_config.HrpsysConfigurator.waitForRTCManagerAndRoboHardware().
def python.hrpsys_config.HrpsysConfigurator.isCalibDone (self)
Check whether joints have been calibrated.
Returns:
bool: True if all joints are calibrated
References python.hrpsys_config.HrpsysConfigurator.simulation_mode.
Referenced by python.hrpsys_config.HrpsysConfigurator.checkEncoders(), and python.hrpsys_config.HrpsysConfigurator.servoOn().
def python.hrpsys_config.HrpsysConfigurator.isServoOn (self, jname = 'any')
Check whether servo control has been turned on.
Parameters:
jname str: Name of a link (that can be obtained by "hiro.Groups" as lists of groups).
Returns:
bool: True if servo is on
References python.hrpsys_config.HrpsysConfigurator.configurator_name, python.hrpsys_config.HrpsysConfigurator.getActualState(), and python.hrpsys_config.HrpsysConfigurator.simulation_mode.
Referenced by python.hrpsys_config.HrpsysConfigurator.checkEncoders(), python.hrpsys_config.HrpsysConfigurator.servoOff(), and python.hrpsys_config.HrpsysConfigurator.servoOn().
def python.hrpsys_config.HrpsysConfigurator.lengthDigitalInput (self)
Returns the length of digital input port.
def python.hrpsys_config.HrpsysConfigurator.lengthDigitalOutput (self)
Returns the length of digital output port.
Referenced by python.hrpsys_config.HrpsysConfigurator.writeDigitalOutput(), and python.hrpsys_config.HrpsysConfigurator.writeDigitalOutputWithMask().
def python.hrpsys_config.HrpsysConfigurator.loadPattern (self, fname, tm)
Load a pattern file that is created offline.
Format of the pattern file:
example format:
  t0 j0 j1 j2...jn
  t1 j0 j1 j2...jn
  :
  tn j0 j1 j2...jn
Delimmitted by space
Each line consists of an action.
Time between each action is defined by tn+1 - tn
The time taken for the 1st line is defined by the arg tm.
Parameters:
fname str: Name of the pattern file.
tm float: - The time to take for the 1st line.
Returns:
: List of 2 oct(string) values.
def python.hrpsys_config.HrpsysConfigurator.playPattern (self, jointangles, rpy, zmp, tm)
Play motion pattern using a given trajectory that is represented by a list of joint angles, rpy, zmp and time.
Parameters:
jointangles list of list of float: The whole list represents a trajectory. Each element of the 1st degree in the list consists of the joint angles.
rpy list of float: Orientation in rpy.
zmp list of float: TODO: description
tm float: Time to complete the task.
Returns:
bool:
def python.hrpsys_config.HrpsysConfigurator.playPatternOfGroup (self, gname, jointangles, tm)
Play motion pattern using a given trajectory that is represented by a list of joint angles.
Parameters:
gname str: Name of the joint group.
jointangles list of list of float: The whole list represents a trajectory. Each element of the 1st degree in the list consists of the joint angles. To illustrate:
[[a0-0, a0-1,...,a0-n], # a)ngle. 1st path in trajectory [a1-0, a1-1,...,a1-n], # 2nd path in the trajectory. : [am-0, am-1,...,am-n]] # mth path in the trajectory
Parameters:
tm float: Time to complete the task.
Returns:
bool:
def python.hrpsys_config.HrpsysConfigurator.readDigitalInput (self)
Read data from Digital Input.
See also:
: HrpsysConfigurator.readDigitalInput
Digital input consits of 14 bits. The last 2 bits are lacking and compensated, so that the last 4 bits are 0x4 instead of 0x1.
Author:
Hajime Saito (@emijah)
Returns:
list of int: List of the values (2 octtets) in digital input register. Range: 0 or 1.
#TODO: Catch AttributeError that occurs when RobotHardware not found. # Typically with simulator, erro msg might look like this; # 'NoneType' object has no attribute 'readDigitalInput'
References python.hrpsys_config.HrpsysConfigurator.simulation_mode.
def python.hrpsys_config.HrpsysConfigurator.readDigitalOutput (self)
Read data from Digital Output.
Digital input consits of 14 bits. The last 2 bits are lacking and compensated, so that the last 4 bits are 0x4 instead of 0x1.
#TODO: Catch AttributeError that occurs when RobotHardware not found. # Typically with simulator, erro msg might look like this; # 'NoneType' object has no attribute 'readDigitaloutput'
Author:
Hajime Saito (@emijah)
Returns:
list of int: List of the values in digital input register. Range: 0 or 1.
def python.hrpsys_config.HrpsysConfigurator.removeForceSensorOffset (self)
remove force sensor offset
def python.hrpsys_config.HrpsysConfigurator.saveLog (self, fname = 'sample')
Save log to the given file name.
Parameters:
fname str: name of the file
References python.hrpsys_config.HrpsysConfigurator.configurator_name.
def python.hrpsys_config.HrpsysConfigurator.servoOff (self, jname = 'all', wait = True)
Turn off servos.
Parameters:
jname str: The value 'all' works iteratively for all servos.
wait bool: Wait for user's confirmation via GUI
Returns:
int: 1 = all arm servo off. 2 = all servo on arms and hands off. -1 = Something wrong happened.
References python.hrpsys_config.HrpsysConfigurator.configurator_name, python.hrpsys_config.HrpsysConfigurator.isServoOn(), and python.hrpsys_config.HrpsysConfigurator.simulation_mode.
def python.hrpsys_config.HrpsysConfigurator.servoOn (self, jname = 'all', destroy = 1, tm = 3)
Turn on servos.
Joints need to be calibrated (otherwise error returns).
Parameters:
jname str: The value 'all' works iteratively for all servos.
destroy int: Not used.
tm float: Second to complete.
Returns:
int: 1 or -1 indicating success or failure, respectively.
References python.hrpsys_config.HrpsysConfigurator.configurator_name, python.hrpsys_config.HrpsysConfigurator.goActual(), python.hrpsys_config.HrpsysConfigurator.isCalibDone(), and python.hrpsys_config.HrpsysConfigurator.isServoOn().
def python.hrpsys_config.HrpsysConfigurator.setJointAngle (self, jname, angle, tm)
Set angle to the given joint.
NOTE-1: It's known that this method does not do anything after
some group operation is done.
TODO: at least need elaborated to warn users.
NOTE-2: that while this method does not check angle value range,
any joints could emit position limit over error, which has not yet
been thrown by hrpsys so that there's no way to catch on this client
side. Worthwhile opening an enhancement ticket for that at
hironx' designated issue tracker.
Parameters:
jname str: name of joint
angle float: In degree.
tm float: Time to complete.
def python.hrpsys_config.HrpsysConfigurator.setJointAngles (self, angles, tm)
Set all joint angles.
NOTE-1: that while this method does not check angle value range,
any joints could emit position limit over error, which has not yet
been thrown by hrpsys so that there's no way to catch on this client
side. Worthwhile opening an enhancement ticket for that at
hironx' designated issue tracker.
Parameters:
angles list of float: In degree.
tm float: Time to complete.
def python.hrpsys_config.HrpsysConfigurator.setJointAnglesOfGroup (self, gname, pose, tm, wait = True)
Set the joint angles to aim.
By default it waits interpolation to be over.
Note that while this method does not check angle value range, any joints could emit position limit over error, which has not yet been handled in hrpsys so that there's no way to catch on this client class level. Please consider opening an enhancement ticket for that at hironx' designated issue tracker.
Parameters:
gname str: Name of the joint group.
pose list of float: list of positions and orientations
tm float: Time to complete.
wait bool: If true, SequencePlayer.waitInterpolationOfGroup gets run. (TODO: Elaborate what this means...Even after having taken a look at its source code I can't tell exactly what it means)
References python.hrpsys_config.HrpsysConfigurator.waitInterpolationOfGroup().
def python.hrpsys_config.HrpsysConfigurator.setSelfGroups (self)
Set to the hrpsys.SequencePlayer the groups of links and joints that are statically defined as member variables (Groups) within this class.
References python.hrpsys_config.HrpsysConfigurator.Groups.
Referenced by python.hrpsys_config.HrpsysConfigurator.init().
def python.hrpsys_config.HrpsysConfigurator.setTargetPose (self, gname, pos, rpy, tm, frame_name = None)
Set absolute pose to a joint.
All d* arguments are in meter.
Parameters:
gname str: Name of the joint group.
pos list of float: In meter.
rpy list of float: In radian.
tm float: Second to complete.
frame_name str: Name of the frame that this particular command reference to.
Returns:
bool: False if unreachable.
Referenced by python.hrpsys_config.HrpsysConfigurator.setTargetPoseRelative().
def python.hrpsys_config.HrpsysConfigurator.setTargetPoseRelative (self, gname, eename, dx = 0, dy = 0, dz = 0, dr = 0, dp = 0, dw = 0, tm = 10, wait = True)
Set angles to a joint group relative to its current pose.
For d*, distance arguments are in meter while rotations are in degree.
Example usage: The following moves RARM_JOINT5 joint 0.1mm forward within 0.1sec.
    robot.setTargetPoseRelative('rarm', 'RARM_JOINT5', dx=0.0001, tm=0.1)
Parameters:
gname str: Name of the joint group.
eename str: Name of the link.
dx float: In meter.
dy float: In meter.
dz float: In meter.
dr float: In radian.
dp float: In radian.
dw float: In radian.
tm float: Second to complete.
wait bol: If true, SequencePlayer.waitInterpolationOfGroup gets run.
Returns:
bool: False if unreachable.
References python::hrpsys_config.euler_from_matrix(), python.hrpsys_config.HrpsysConfigurator.setTargetPose(), and python.hrpsys_config.HrpsysConfigurator.waitInterpolationOfGroup().
def python.hrpsys_config.HrpsysConfigurator.setupLogger (self)
Setup logging function.
References python.hrpsys_config.HrpsysConfigurator.abc, python.hrpsys_config.HrpsysConfigurator.configurator_name, python.hrpsys_config.HrpsysConfigurator.connectLoggerPort(), python.hrpsys_config.HrpsysConfigurator.kf, python.hrpsys_config.HrpsysConfigurator.log, python.hrpsys_config.HrpsysConfigurator.rh, python.hrpsys_config.HrpsysConfigurator.rmfo, python.hrpsys_config.HrpsysConfigurator.sensors, python.hrpsys_config.HrpsysConfigurator.seq, python.hrpsys_config.HrpsysConfigurator.sh, and python.hrpsys_config.HrpsysConfigurator.st.
Referenced by python.hrpsys_config.HrpsysConfigurator.init().
def python.hrpsys_config.HrpsysConfigurator.waitForModelLoader (self)
Wait for ModelLoader.
References python.hrpsys_config.HrpsysConfigurator.configurator_name, and python.hrpsys_config.HrpsysConfigurator.findModelLoader().
Referenced by python.hrpsys_config.HrpsysConfigurator.init().
def python.hrpsys_config.HrpsysConfigurator.waitForRobotHardware (self, robotname = "Robot")
Wait for RobotHardware is exists and activated.
Parameters:
robotname str: name of RobotHardware component.
References python.hrpsys_config.HrpsysConfigurator.configurator_name, python.hrpsys_config.HrpsysConfigurator.ms, and python.hrpsys_config.HrpsysConfigurator.rh.
Referenced by python.hrpsys_config.HrpsysConfigurator.waitForRTCManagerAndRoboHardware().
def python.hrpsys_config.HrpsysConfigurator.waitForRTCManager (self, managerhost = nshost)
Wait for RTC manager.
Parameters:
managerhost str: name of host computer that manager is running
References python.hrpsys_config.HrpsysConfigurator.configurator_name, and python.hrpsys_config.HrpsysConfigurator.ms.
Referenced by python.hrpsys_config.HrpsysConfigurator.waitForRTCManagerAndRoboHardware().
def python.hrpsys_config.HrpsysConfigurator.waitForRTCManagerAndRoboHardware (self, robotname = "Robot", managerhost = nshost)
Wait for both RTC Manager (waitForRTCManager()) and RobotHardware (waitForRobotHardware())
Parameters:
managerhost str: name of host computer that manager is running
robotname str: name of RobotHardware component.
References python.hrpsys_config.HrpsysConfigurator.checkSimulationMode(), python.hrpsys_config.HrpsysConfigurator.waitForRobotHardware(), and python.hrpsys_config.HrpsysConfigurator.waitForRTCManager().
Referenced by python.hrpsys_config.HrpsysConfigurator.init().
def python.hrpsys_config.HrpsysConfigurator.waitInterpolation (self)
Lets SequencePlayer wait until the movement currently happening to finish.
def python.hrpsys_config.HrpsysConfigurator.waitInterpolationOfGroup (self, gname)
Lets SequencePlayer wait until the movement currently happening to finish.
See also:
: SequencePlayer.waitInterpolationOfGroup
: http://wiki.ros.org/joint_trajectory_action. This method corresponds to JointTrajectoryGoal in ROS.
Parameters:
gname str: Name of the joint group.
Referenced by python.hrpsys_config.HrpsysConfigurator.setJointAnglesOfGroup(), and python.hrpsys_config.HrpsysConfigurator.setTargetPoseRelative().
def python.hrpsys_config.HrpsysConfigurator.writeDigitalOutput (self, dout)
Using writeDigitalOutputWithMask is recommended for the less data transport.
Parameters:
dout list of int: List of bits, length of 32 bits where elements are 0 or 1.
What each element stands for depends on how the robot's imlemented. Consult the hardware manual.
Returns:
bool: RobotHardware.writeDigitalOutput returns True if writable. False otherwise.
References python.hrpsys_config.HrpsysConfigurator.lengthDigitalOutput(), and python.hrpsys_config.HrpsysConfigurator.simulation_mode.
def python.hrpsys_config.HrpsysConfigurator.writeDigitalOutputWithMask (self, dout, mask)
Both dout and mask are lists with length of 32.
Only the bit in dout that corresponds to the bits in mask that are flagged as 1 will be evaluated.
Example:
 Case-1. Only 18th bit will be evaluated as 1.
  dout [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
  mask [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
 Case-2. Only 18th bit will be evaluated as 0.
  dout [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
  mask [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
 Case-3. None will be evaluated since there's no flagged bit in mask.
  dout [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
  mask [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Parameters:
dout list of int: List of bits, length of 32 bits where elements are 0 or 1.
mask list of int: List of masking bits, length of 32 bits where elements are 0 or 1.
Returns:
bool: RobotHardware.writeDigitalOutput returns True if writable. False otherwise.
References python.hrpsys_config.HrpsysConfigurator.lengthDigitalOutput(), and python.hrpsys_config.HrpsysConfigurator.simulation_mode.
Member Data Documentation
python::hrpsys_config.HrpsysConfigurator::abc = None [static]
Referenced by python.hrpsys_config.HrpsysConfigurator.connectComps(), python.hrpsys_config.HrpsysConfigurator.getJointAngleControllerList(), and python.hrpsys_config.HrpsysConfigurator.setupLogger().
python::hrpsys_config.HrpsysConfigurator::abc_version = None [static]
python::hrpsys_config.HrpsysConfigurator::co = None [static]
Referenced by python.hrpsys_config.HrpsysConfigurator.connectComps(), and python.hrpsys_config.HrpsysConfigurator.getJointAngleControllerList().
python::hrpsys_config.HrpsysConfigurator::co_svc = None [static]
python::hrpsys_config.HrpsysConfigurator::co_version = None [static]
python::hrpsys_config.HrpsysConfigurator::configurator_name
Referenced by python.hrpsys_config.HrpsysConfigurator::checkEncoders(), python.hrpsys_config.HrpsysConfigurator::checkSimulationMode(), python.hrpsys_config.HrpsysConfigurator::connectComps(), python.hrpsys_config.HrpsysConfigurator::connectLoggerPort(), python.hrpsys_config.HrpsysConfigurator::createComp(), python.hrpsys_config.HrpsysConfigurator::createComps(), python.hrpsys_config.HrpsysConfigurator::findComp(), python.hrpsys_config.HrpsysConfigurator::findComps(), python.hrpsys_config.HrpsysConfigurator::getBodyInfo(), python.hrpsys_config.HrpsysConfigurator::init(), python.hrpsys_config.HrpsysConfigurator::isServoOn(), python.hrpsys_config.HrpsysConfigurator::saveLog(), python.hrpsys_config.HrpsysConfigurator::servoOff(), python.hrpsys_config.HrpsysConfigurator::servoOn(), python.hrpsys_config.HrpsysConfigurator::setupLogger(), python.hrpsys_config.HrpsysConfigurator::waitForModelLoader(), python.hrpsys_config.HrpsysConfigurator::waitForRobotHardware(), and python.hrpsys_config.HrpsysConfigurator::waitForRTCManager().
python::hrpsys_config.HrpsysConfigurator::el = None [static]
Referenced by python.hrpsys_config.HrpsysConfigurator.connectComps(), and python.hrpsys_config.HrpsysConfigurator.getJointAngleControllerList().
python::hrpsys_config.HrpsysConfigurator::el_svc = None [static]
python::hrpsys_config.HrpsysConfigurator::el_version = None [static]
python::hrpsys_config.HrpsysConfigurator::ep_svc = None [static]
Referenced by python.hrpsys_config.HrpsysConfigurator.checkSimulationMode().
python::hrpsys_config.HrpsysConfigurator::fk = None [static]
Referenced by python.hrpsys_config.HrpsysConfigurator.connectComps().
python::hrpsys_config.HrpsysConfigurator::fk_svc = None [static]
python::hrpsys_config.HrpsysConfigurator::fk_version = None [static]
Referenced by python.hrpsys_config.HrpsysConfigurator.getCurrentPose(), and python.hrpsys_config.HrpsysConfigurator.getReferencePose().
python::hrpsys_config.HrpsysConfigurator::gc = None [static]
Referenced by python.hrpsys_config.HrpsysConfigurator.connectComps(), and python.hrpsys_config.HrpsysConfigurator.getJointAngleControllerList().
python::hrpsys_config.HrpsysConfigurator::gc_svc = None [static]
python::hrpsys_config.HrpsysConfigurator::gc_version = None [static]
list python::hrpsys_config.HrpsysConfigurator::Groups = [] [static]
Referenced by python.hrpsys_config.HrpsysConfigurator.flat2Groups(), python.hrpsys_config.HrpsysConfigurator.getCurrentPose(), python.hrpsys_config.HrpsysConfigurator.getCurrentPosition(), python.hrpsys_config.HrpsysConfigurator.getCurrentRotation(), python.hrpsys_config.HrpsysConfigurator.getCurrentRPY(), python.hrpsys_config.HrpsysConfigurator.getReferencePose(), python.hrpsys_config.HrpsysConfigurator.getReferencePosition(), python.hrpsys_config.HrpsysConfigurator.getReferenceRotation(), python.hrpsys_config.HrpsysConfigurator.getReferenceRPY(), and python.hrpsys_config.HrpsysConfigurator.setSelfGroups().
python::hrpsys_config.HrpsysConfigurator::hgc = None [static]
Referenced by python.hrpsys_config.HrpsysConfigurator.checkSimulationMode().
python::hrpsys_config.HrpsysConfigurator::ic = None [static]
Referenced by python.hrpsys_config.HrpsysConfigurator.connectComps(), and python.hrpsys_config.HrpsysConfigurator.getJointAngleControllerList().
python::hrpsys_config.HrpsysConfigurator::ic_version = None [static]
python::hrpsys_config.HrpsysConfigurator::kf = None [static]
Referenced by python.hrpsys_config.HrpsysConfigurator.connectComps(), and python.hrpsys_config.HrpsysConfigurator.setupLogger().
python::hrpsys_config.HrpsysConfigurator::kf_version = None [static]
python::hrpsys_config.HrpsysConfigurator::log = None [static]
Referenced by python.hrpsys_config.HrpsysConfigurator.connectLoggerPort(), and python.hrpsys_config.HrpsysConfigurator.setupLogger().
python::hrpsys_config.HrpsysConfigurator::log_svc = None [static]
python::hrpsys_config.HrpsysConfigurator::log_version = None [static]
python::hrpsys_config.HrpsysConfigurator::ms = None [static]
Referenced by python.hrpsys_config.HrpsysConfigurator.waitForRobotHardware(), and python.hrpsys_config.HrpsysConfigurator.waitForRTCManager().
python::hrpsys_config.HrpsysConfigurator::pdc = None [static]
Referenced by python.hrpsys_config.HrpsysConfigurator.checkSimulationMode(), and python.hrpsys_config.HrpsysConfigurator.connectComps().
python::hrpsys_config.HrpsysConfigurator::rh = None [static]
Referenced by python.hrpsys_config.HrpsysConfigurator::checkSimulationMode(), python.hrpsys_config.HrpsysConfigurator::connectComps(), python.hrpsys_config.HrpsysConfigurator::getRTCInstanceList(), python.hrpsys_config.HrpsysConfigurator::setupLogger(), and python.hrpsys_config.HrpsysConfigurator::waitForRobotHardware().
python::hrpsys_config.HrpsysConfigurator::rh_svc = None [static]
Referenced by python.hrpsys_config.HrpsysConfigurator.checkSimulationMode().
python::hrpsys_config.HrpsysConfigurator::rh_version = None [static]
python::hrpsys_config.HrpsysConfigurator::rmfo = None [static]
Referenced by python.hrpsys_config.HrpsysConfigurator.connectComps(), and python.hrpsys_config.HrpsysConfigurator.setupLogger().
python::hrpsys_config.HrpsysConfigurator::rmfo_version = None [static]
python::hrpsys_config.HrpsysConfigurator::sensors = None [static]
Referenced by python.hrpsys_config.HrpsysConfigurator.connectComps(), python.hrpsys_config.HrpsysConfigurator.init(), and python.hrpsys_config.HrpsysConfigurator.setupLogger().
python::hrpsys_config.HrpsysConfigurator::seq = None [static]
Referenced by python.hrpsys_config.HrpsysConfigurator.connectComps(), and python.hrpsys_config.HrpsysConfigurator.setupLogger().
python::hrpsys_config.HrpsysConfigurator::seq_svc = None [static]
python::hrpsys_config.HrpsysConfigurator::seq_version = None [static]
python::hrpsys_config.HrpsysConfigurator::sh = None [static]
Referenced by python.hrpsys_config.HrpsysConfigurator.connectComps(), and python.hrpsys_config.HrpsysConfigurator.setupLogger().
python::hrpsys_config.HrpsysConfigurator::sh_svc = None [static]
python::hrpsys_config.HrpsysConfigurator::sh_version = None [static]
python::hrpsys_config.HrpsysConfigurator::simulation_mode = None [static]
Referenced by python.hrpsys_config.HrpsysConfigurator.checkSimulationMode(), python.hrpsys_config.HrpsysConfigurator.connectComps(), python.hrpsys_config.HrpsysConfigurator.isCalibDone(), python.hrpsys_config.HrpsysConfigurator.isServoOn(), python.hrpsys_config.HrpsysConfigurator.readDigitalInput(), python.hrpsys_config.HrpsysConfigurator.servoOff(), python.hrpsys_config.HrpsysConfigurator.writeDigitalOutput(), and python.hrpsys_config.HrpsysConfigurator.writeDigitalOutputWithMask().
python::hrpsys_config.HrpsysConfigurator::st = None [static]
Referenced by python.hrpsys_config.HrpsysConfigurator.connectComps(), python.hrpsys_config.HrpsysConfigurator.getJointAngleControllerList(), and python.hrpsys_config.HrpsysConfigurator.setupLogger().
python::hrpsys_config.HrpsysConfigurator::st_version = None [static]
python::hrpsys_config.HrpsysConfigurator::tc = None [static]
Referenced by python.hrpsys_config.HrpsysConfigurator.connectComps(), and python.hrpsys_config.HrpsysConfigurator.getJointAngleControllerList().
python::hrpsys_config.HrpsysConfigurator::tc_svc = None [static]
python::hrpsys_config.HrpsysConfigurator::tc_version = None [static]
python::hrpsys_config.HrpsysConfigurator::te = None [static]
Referenced by python.hrpsys_config.HrpsysConfigurator.connectComps().
python::hrpsys_config.HrpsysConfigurator::te_svc = None [static]
python::hrpsys_config.HrpsysConfigurator::te_version = None [static]
python::hrpsys_config.HrpsysConfigurator::tf = None [static]
Referenced by python.hrpsys_config.HrpsysConfigurator.connectComps().
python::hrpsys_config.HrpsysConfigurator::tf_version = None [static]
python::hrpsys_config.HrpsysConfigurator::tl = None [static]
Referenced by python.hrpsys_config.HrpsysConfigurator.connectComps().
python::hrpsys_config.HrpsysConfigurator::tl_svc = None [static]
python::hrpsys_config.HrpsysConfigurator::tl_version = None [static]
python::hrpsys_config.HrpsysConfigurator::vs = None [static]
Referenced by python.hrpsys_config.HrpsysConfigurator.connectComps().
python::hrpsys_config.HrpsysConfigurator::vs_version = None [static]
The documentation for this class was generated from the following file:
hrpsys_config.py